apiVersion: v1
kind: Service
metadata:
  name: {{ include "northprojects.fullname" . }}-static
  labels:
{{ include "northprojects.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "northprojects.name" . }}-static
    app.kubernetes.io/instance: {{ .Release.Name }}
