# Generated by Django 2.2.4 on 2019-08-22 06:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [("footer", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="logo_img",
            field=wagtail.core.fields.StreamField(
                [
                   
                ],
                blank=True,
                null=True,
            ),
        )
    ]
