# Generated by Django 2.2.4 on 2019-08-26 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_footer_logo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='logo_img',
        ),
    ]
