# Generated by Django 2.2.4 on 2019-08-22 14:27

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190822_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Hero', wagtail.core.blocks.StructBlock([('hero_img', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('paragraph', wagtail.core.blocks.CharBlock(required=False))])), ('TwoCol_2', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('col1', wagtail.core.blocks.CharBlock(required=False)), ('col2', wagtail.core.blocks.CharBlock(required=False))])), ('ImgText_3', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('preamble', wagtail.core.blocks.RichTextBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('call_to_action', wagtail.core.blocks.PageChooserBlock(required=False)), ('order', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left Image'), ('right', 'Right Image')]))])), ('ImgOnText_4', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', default='')), ('preamble', wagtail.core.blocks.RichTextBlock(required=False))])), ('Staff_6', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', required=False))])), ('CImgText_8', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('richtext', wagtail.core.blocks.RichTextBlock(required=False)), ('order', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left Image'), ('right', 'Right Image')]))])), ('ImgColorText_9', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('preamble', wagtail.core.blocks.RichTextBlock(required=False)), ('call_to_action', wagtail.core.blocks.PageChooserBlock(required=False)), ('order', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left Image'), ('right', 'Right Image')]))])), ('DoubleImgText_10', wagtail.core.blocks.StructBlock([('image1', wagtail.images.blocks.ImageChooserBlock()), ('image2', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('preamble', wagtail.core.blocks.RichTextBlock(required=False)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=False)), ('order', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left Image'), ('right', 'Right Image')]))])), ('USP_12', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(classname='full title', required=False)), ('paragraph', wagtail.core.blocks.CharBlock(required=False)), ('question1', wagtail.core.blocks.CharBlock(required=False)), ('paragraph1', wagtail.core.blocks.CharBlock(required=False)), ('question2', wagtail.core.blocks.CharBlock(required=False)), ('paragraph2', wagtail.core.blocks.CharBlock(required=False)), ('question3', wagtail.core.blocks.CharBlock(required=False)), ('paragraph3', wagtail.core.blocks.CharBlock(required=False)), ('question4', wagtail.core.blocks.CharBlock(required=False)), ('paragraph4', wagtail.core.blocks.RichTextBlock(required=False)), ('order', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left Image'), ('right', 'Right Image')]))]))], blank=True, null=True),
        ),
    ]
